### ISSUE TITLE
(Mojo::Server::Threaded 0.12)Warning: the following files are missing in your kit...

### ISSUE THREAD

**Issue by twata1** [tomk3003/mojo-server-threaded#1]
Hi,

I notieced the following message when I installed Mojo::Server::Threaded on Strawberry Perl 5.26.0(Windows 7(32bit)).

    C:\home\bath>cpan Mojo::Server::Threaded
    CPAN: CPAN::SQLite loaded ok (v0.211)  
    (snip)
    Checking if your kit is complete...
    Warning: the following files are missing in your kit:
            lib/Mojolicious/Command/threaded.pm
    Please inform the author.
    Generating a gmake-style Makefile
    (snip)

I hope this helps.

**Comment by tomk3003** [comment]
Hi twata1,
thanks for the info. 
I fixed the bug already. Version 0.13 will be ready on CPAN in an hour or so.
Thomas
